#! /bin/sh
# ─────────────────────────────────────────────────────────────────
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
# ─────────────────────────────────────────────────────────────────
#
# Config author : Wakana Shimamura
# Configs repo  : https://github.com/wakanashimamura/bspwm_dotfiles
# File          : bspwmrc
# Compatible    : BSPWM 0.9.11
# Description   : Configuration settings for bspwm
#
# ─────────────────────────────────────────────────────────────────

# ┌──────────────────────────────────────────────────────────────────────┐
# │                             AUTOSTART APPS                           │
# └──────────────────────────────────────────────────────────────────────┘

# Wallpaper
feh --no-fehbg --bg-fill $HOME/.wallpaper/sekiro.jpg

# Run sxhkd daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Run polybra.
killall -q polybar
polybar -config $HOME/.config/polybar/config.ini & 

# Run picom
picom --config $HOME/.config/picom/picom.conf & 

# Fix cursor.
xsetroot -cursor_name left_ptr 

# ┌──────────────────────────────────────────────────────────────────────┐
# │                              WORKSPACES                              │
# └──────────────────────────────────────────────────────────────────────┘

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config external_rules_command $HOME/.config/bspwm/external_rules

bspc config remove_disabled_monitors   false
bspc config remove_unplugged_monitors  false

# ┌──────────────────────────────────────────────────────────────────────┐
# │                            SPLIT BEHAVIOR                            │
# └──────────────────────────────────────────────────────────────────────┘

bspc config split_ratio         0.50
bspc config automatic_scheme    longest_side
bspc config initial_polarity    second_child
bspc config removal_adjustment  true
bspc config presel_feedback     true

# ┌──────────────────────────────────────────────────────────────────────┐
# │                                EVENTS                                │
# └──────────────────────────────────────────────────────────────────────┘

bspc config mapping_events_count    -1
bspc config ignore_ewmh_focus       true
bspc config ignore_ewmh_fullscreen  none
bspc config ignore_ewmh_struts      false

# ┌──────────────────────────────────────────────────────────────────────┐
# │                            MONOCULAR MODES                           │
# └──────────────────────────────────────────────────────────────────────┘
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config top_monocle_padding  10

# ┌──────────────────────────────────────────────────────────────────────┐
# │                                 MOUSE                                │
# └──────────────────────────────────────────────────────────────────────┘


bspc config pointer_modifier  mod4
bspc config pointer_action1   move
bspc config pointer_action2   resize_side
bspc config pointer_action3   resize_corner

bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  false

# ┌──────────────────────────────────────────────────────────────────────┐
# │                      WINDOW BORDERS AND MARGINS                      │
# └──────────────────────────────────────────────────────────────────────┘

bspc config border_width  1
bspc config window_gap    10

bspc config top_padding     2
bspc config bottom_padding  2
bspc config left_padding    2
bspc config right_padding   2

# ┌──────────────────────────────────────────────────────────────────────┐
# │                                COLORS                                │
# └──────────────────────────────────────────────────────────────────────┘

bspc config normal_border_color    "#11111b"
bspc config active_border_color    "#cba6f7"
bspc config focused_border_color   "#cba6f7"
bspc config presel_feedback_color  "#2f1f59"
